//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyDeliveryUI.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasyDeliveryUI.Resx.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boat.
        /// </summary>
        internal static string BoatText {
            get {
                return ResourceManager.GetString("BoatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        internal static string ButtonSignOut {
            get {
                return ResourceManager.GetString("ButtonSignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create account.
        /// </summary>
        internal static string CreateButtons {
            get {
                return ResourceManager.GetString("CreateButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery.
        /// </summary>
        internal static string DeliveryText {
            get {
                return ResourceManager.GetString("DeliveryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managed the delivery of the stuff you can&apos;t fit into your car..
        /// </summary>
        internal static string DescriptionDelivery {
            get {
                return ResourceManager.GetString("DescriptionDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For packages from 0 to 70 pounds, this service arrives within 24 to 48 hours from the USA..
        /// </summary>
        internal static string DescriptionPountsText {
            get {
                return ResourceManager.GetString("DescriptionPountsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can track your package with the number of traking.
        /// </summary>
        internal static string DescriptionTrackPackage {
            get {
                return ResourceManager.GetString("DescriptionTrackPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string EntryEmail {
            get {
                return ResourceManager.GetString("EntryEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Card.
        /// </summary>
        internal static string EntryID_Card {
            get {
                return ResourceManager.GetString("EntryID_Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastname.
        /// </summary>
        internal static string EntrylLastname {
            get {
                return ResourceManager.GetString("EntrylLastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string EntryPassword {
            get {
                return ResourceManager.GetString("EntryPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string EntryPhone {
            get {
                return ResourceManager.GetString("EntryPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string EntryUsername {
            get {
                return ResourceManager.GetString("EntryUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        internal static string LabelForgotPass {
            get {
                return ResourceManager.GetString("LabelForgotPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OR.
        /// </summary>
        internal static string LabelOr {
            get {
                return ResourceManager.GetString("LabelOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string LabelRegister {
            get {
                return ResourceManager.GetString("LabelRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string LabelSignUp {
            get {
                return ResourceManager.GetString("LabelSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and conditions.
        /// </summary>
        internal static string LabelTerms {
            get {
                return ResourceManager.GetString("LabelTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package.
        /// </summary>
        internal static string PackageText {
            get {
                return ResourceManager.GetString("PackageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package pounts.
        /// </summary>
        internal static string PountsText {
            get {
                return ResourceManager.GetString("PountsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to store.
        /// </summary>
        internal static string StoreText {
            get {
                return ResourceManager.GetString("StoreText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovery.
        /// </summary>
        internal static string TitleDiscovery {
            get {
                return ResourceManager.GetString("TitleDiscovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string TitleHome {
            get {
                return ResourceManager.GetString("TitleHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string TitleProfile {
            get {
                return ResourceManager.GetString("TitleProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reception.
        /// </summary>
        internal static string TitleReception {
            get {
                return ResourceManager.GetString("TitleReception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track package.
        /// </summary>
        internal static string TrackPackageText {
            get {
                return ResourceManager.GetString("TrackPackageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck.
        /// </summary>
        internal static string TruckText {
            get {
                return ResourceManager.GetString("TruckText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete field email o incorrect email.
        /// </summary>
        internal static string ValidateEmail {
            get {
                return ResourceManager.GetString("ValidateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete field id car o incorrect id Car..
        /// </summary>
        internal static string ValidateIscardNumber {
            get {
                return ResourceManager.GetString("ValidateIscardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete field password or password is not equal..
        /// </summary>
        internal static string ValidatePassword {
            get {
                return ResourceManager.GetString("ValidatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete field number o incorrect number..
        /// </summary>
        internal static string ValidatePhoneNumber {
            get {
                return ResourceManager.GetString("ValidatePhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete field nombre or lastname..
        /// </summary>
        internal static string ValidateUsername {
            get {
                return ResourceManager.GetString("ValidateUsername", resourceCulture);
            }
        }
    }
}
